language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: python setup.py test; rm -rf eggs-directory ; rm -rf download-cache ; rm .installed.cfg; export PLOCK_TIMEOUT=450 ; plock .
